on:
      push:
        branches:
          - main
jobs:
      deploy:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Set up Terraform
          uses: hashicorp/setup-terraform@v2

        - name: Initialize Terraform
          run: terraform -chdir=terraform init

        - name: Validate Terraform
          run: terraform -chdir=terraform validate

        - name: Plan Terraform
          run: terraform -chdir=terraform plan

        - name: Apply Terraform
          run: terraform -chdir=terraform apply -auto-approve
